# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Graph_Calculator(object):
    def setupUi(self, Graph_Calculator):
        Graph_Calculator.setObjectName("Graph_Calculator")
        Graph_Calculator.resize(941, 567)
        self.confirm_cancel = QtWidgets.QDialogButtonBox(Graph_Calculator)
        self.confirm_cancel.setGeometry(QtCore.QRect(720, 510, 171, 41))
        self.confirm_cancel.setOrientation(QtCore.Qt.Horizontal)
        self.confirm_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirm_cancel.setObjectName("confirm_cancel")
        self.lb_window = QtWidgets.QLabel(Graph_Calculator)
        self.lb_window.setGeometry(QtCore.QRect(20, 20, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Euphemia")
        font.setPointSize(22)
        self.lb_window.setFont(font)
        self.lb_window.setObjectName("lb_window")
        self.lb_calc = QtWidgets.QLabel(Graph_Calculator)
        self.lb_calc.setGeometry(QtCore.QRect(40, 80, 851, 101))
        self.lb_calc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lb_calc.setText("")
        self.lb_calc.setObjectName("lb_calc")
        self.gridLayoutWidget = QtWidgets.QWidget(Graph_Calculator)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 250, 224, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.i_rotate = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.i_rotate.setProperty("value", 1)
        self.i_rotate.setObjectName("i_rotate")
        self.gridLayout.addWidget(self.i_rotate, 4, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 4, 2, 1, 1)
        self.btn_rotate_sp = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_rotate_sp.setObjectName("btn_rotate_sp")
        self.gridLayout.addWidget(self.btn_rotate_sp, 4, 0, 1, 1)
        self.btn_trim = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_trim.setObjectName("btn_trim")
        self.gridLayout.addWidget(self.btn_trim, 2, 0, 1, 1)
        self.btn_minkowski = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_minkowski.setObjectName("btn_minkowski")
        self.gridLayout.addWidget(self.btn_minkowski, 1, 0, 1, 1)
        self.btn_rotate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_rotate.setObjectName("btn_rotate")
        self.gridLayout.addWidget(self.btn_rotate, 3, 0, 1, 1)
        self.btn_union = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_union.setObjectName("btn_union")
        self.gridLayout.addWidget(self.btn_union, 0, 0, 1, 1)
        self.btn_undo = QtWidgets.QPushButton(Graph_Calculator)
        self.btn_undo.setGeometry(QtCore.QRect(540, 500, 121, 41))
        self.btn_undo.setObjectName("btn_undo")
        self.graphs = QtWidgets.QFrame(Graph_Calculator)
        self.graphs.setGeometry(QtCore.QRect(400, 250, 471, 211))
        self.graphs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphs.setObjectName("graphs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.graphs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_U = QtWidgets.QPushButton(self.graphs)
        self.btn_U.setObjectName("btn_U")
        self.gridLayout_2.addWidget(self.btn_U, 1, 1, 1, 1)
        self.btn_V = QtWidgets.QPushButton(self.graphs)
        self.btn_V.setObjectName("btn_V")
        self.gridLayout_2.addWidget(self.btn_V, 1, 2, 1, 1)
        self.btn_W = QtWidgets.QPushButton(self.graphs)
        self.btn_W.setObjectName("btn_W")
        self.gridLayout_2.addWidget(self.btn_W, 1, 3, 1, 1)
        self.btn_J = QtWidgets.QPushButton(self.graphs)
        self.btn_J.setObjectName("btn_J")
        self.gridLayout_2.addWidget(self.btn_J, 0, 1, 1, 1)
        self.btn_H = QtWidgets.QPushButton(self.graphs)
        self.btn_H.setObjectName("btn_H")
        self.gridLayout_2.addWidget(self.btn_H, 0, 0, 1, 1)
        self.btn_L = QtWidgets.QPushButton(self.graphs)
        self.btn_L.setObjectName("btn_L")
        self.gridLayout_2.addWidget(self.btn_L, 0, 3, 1, 1)
        self.btn_T = QtWidgets.QPushButton(self.graphs)
        self.btn_T.setObjectName("btn_T")
        self.gridLayout_2.addWidget(self.btn_T, 1, 0, 1, 1)
        self.btn_K = QtWidgets.QPushButton(self.graphs)
        self.btn_K.setObjectName("btn_K")
        self.gridLayout_2.addWidget(self.btn_K, 0, 2, 1, 1)
        self.btn_M = QtWidgets.QPushButton(self.graphs)
        self.btn_M.setObjectName("btn_M")
        self.gridLayout_2.addWidget(self.btn_M, 2, 0, 1, 1)
        self.btn_pentagon = QtWidgets.QPushButton(self.graphs)
        self.btn_pentagon.setObjectName("btn_pentagon")
        self.gridLayout_2.addWidget(self.btn_pentagon, 2, 1, 1, 1)
        self.btn_pentagram = QtWidgets.QPushButton(self.graphs)
        self.btn_pentagram.setObjectName("btn_pentagram")
        self.gridLayout_2.addWidget(self.btn_pentagram, 2, 2, 1, 1)
        self.btn_petersen = QtWidgets.QPushButton(self.graphs)
        self.btn_petersen.setObjectName("btn_petersen")
        self.gridLayout_2.addWidget(self.btn_petersen, 2, 3, 1, 1)
        self.btn_moser = QtWidgets.QPushButton(self.graphs)
        self.btn_moser.setObjectName("btn_moser")
        self.gridLayout_2.addWidget(self.btn_moser, 3, 0, 1, 1)

        self.retranslateUi(Graph_Calculator)
        self.confirm_cancel.accepted.connect(Graph_Calculator.accept)
        self.confirm_cancel.rejected.connect(Graph_Calculator.reject)
        QtCore.QMetaObject.connectSlotsByName(Graph_Calculator)

    def retranslateUi(self, Graph_Calculator):
        _translate = QtCore.QCoreApplication.translate
        Graph_Calculator.setWindowTitle(_translate("Graph_Calculator", "Graph Calculator"))
        self.lb_window.setText(_translate("Graph_Calculator", "Unit Distance Graph Calculator"))
        self.btn_rotate_sp.setText(_translate("Graph_Calculator", "Special Rotate"))
        self.btn_trim.setText(_translate("Graph_Calculator", "Trim"))
        self.btn_minkowski.setText(_translate("Graph_Calculator", "Minkowski Sum"))
        self.btn_rotate.setText(_translate("Graph_Calculator", "Rotate"))
        self.btn_union.setText(_translate("Graph_Calculator", "Union"))
        self.btn_undo.setText(_translate("Graph_Calculator", "Undo"))
        self.btn_U.setText(_translate("Graph_Calculator", "U"))
        self.btn_V.setText(_translate("Graph_Calculator", "V"))
        self.btn_W.setText(_translate("Graph_Calculator", "W"))
        self.btn_J.setText(_translate("Graph_Calculator", "J"))
        self.btn_H.setText(_translate("Graph_Calculator", "H"))
        self.btn_L.setText(_translate("Graph_Calculator", "L"))
        self.btn_T.setText(_translate("Graph_Calculator", "T"))
        self.btn_K.setText(_translate("Graph_Calculator", "K"))
        self.btn_M.setText(_translate("Graph_Calculator", "M"))
        self.btn_pentagon.setText(_translate("Graph_Calculator", "Pentagon"))
        self.btn_pentagram.setText(_translate("Graph_Calculator", "Pentagram"))
        self.btn_petersen.setText(_translate("Graph_Calculator", "Petersen Graph"))
        self.btn_moser.setText(_translate("Graph_Calculator", "Moser\'s Spindle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Graph_Calculator = QtWidgets.QDialog()
    ui = Ui_Graph_Calculator()
    ui.setupUi(Graph_Calculator)
    Graph_Calculator.show()
    sys.exit(app.exec_())

