# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphs.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GraphsDialog(object):
    def setupUi(self, GraphsDialog):
        GraphsDialog.setObjectName("GraphsDialog")
        GraphsDialog.resize(1050, 666)
        self.lb_window = QtWidgets.QLabel(GraphsDialog)
        self.lb_window.setGeometry(QtCore.QRect(20, 20, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Euphemia")
        font.setPointSize(22)
        self.lb_window.setFont(font)
        self.lb_window.setObjectName("lb_window")
        self.gridLayoutWidget = QtWidgets.QWidget(GraphsDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 120, 421, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridGrey = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridGrey.setContentsMargins(0, 0, 0, 0)
        self.gridGrey.setObjectName("gridGrey")
        self.btn_T = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_T.setObjectName("btn_T")
        self.gridGrey.addWidget(self.btn_T, 1, 0, 1, 1)
        self.btn_K = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_K.setObjectName("btn_K")
        self.gridGrey.addWidget(self.btn_K, 0, 2, 1, 1)
        self.btn_L = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_L.setObjectName("btn_L")
        self.gridGrey.addWidget(self.btn_L, 0, 3, 1, 1)
        self.btn_J = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_J.setObjectName("btn_J")
        self.gridGrey.addWidget(self.btn_J, 0, 1, 1, 1)
        self.btn_H = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_H.setObjectName("btn_H")
        self.gridGrey.addWidget(self.btn_H, 0, 0, 1, 1)
        self.btn_V = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_V.setObjectName("btn_V")
        self.gridGrey.addWidget(self.btn_V, 1, 2, 1, 1)
        self.btn_U = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_U.setObjectName("btn_U")
        self.gridGrey.addWidget(self.btn_U, 1, 1, 1, 1)
        self.btn_W = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_W.setObjectName("btn_W")
        self.gridGrey.addWidget(self.btn_W, 1, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(GraphsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(480, 120, 160, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridGrey2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.gridGrey2.setContentsMargins(0, 0, 0, 0)
        self.gridGrey2.setObjectName("gridGrey2")
        self.btn_M = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_M.setObjectName("btn_M")
        self.gridGrey2.addWidget(self.btn_M)
        self.btn_G = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_G.setObjectName("btn_G")
        self.gridGrey2.addWidget(self.btn_G)
        self.lb_degrey = QtWidgets.QLabel(GraphsDialog)
        self.lb_degrey.setGeometry(QtCore.QRect(20, 70, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Euphemia")
        font.setPointSize(14)
        font.setUnderline(True)
        self.lb_degrey.setFont(font)
        self.lb_degrey.setObjectName("lb_degrey")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(GraphsDialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(480, 460, 421, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridAdditional = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridAdditional.setContentsMargins(0, 0, 0, 0)
        self.gridAdditional.setObjectName("gridAdditional")
        self.btn_pentagram = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_pentagram.setObjectName("btn_pentagram")
        self.gridAdditional.addWidget(self.btn_pentagram, 0, 2, 1, 1)
        self.btn_petersen = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_petersen.setObjectName("btn_petersen")
        self.gridAdditional.addWidget(self.btn_petersen, 0, 3, 1, 1)
        self.btn_pentagon = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_pentagon.setObjectName("btn_pentagon")
        self.gridAdditional.addWidget(self.btn_pentagon, 0, 1, 1, 1)
        self.btn_moser = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_moser.setObjectName("btn_moser")
        self.gridAdditional.addWidget(self.btn_moser, 0, 0, 1, 1)
        self.lb_additional = QtWidgets.QLabel(GraphsDialog)
        self.lb_additional.setGeometry(QtCore.QRect(490, 410, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Euphemia")
        font.setPointSize(14)
        font.setUnderline(True)
        self.lb_additional.setFont(font)
        self.lb_additional.setObjectName("lb_additional")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(GraphsDialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 450, 421, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridHeule = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridHeule.setContentsMargins(0, 0, 0, 0)
        self.gridHeule.setObjectName("gridHeule")
        self.btn_S199 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_S199.setObjectName("btn_S199")
        self.gridHeule.addWidget(self.btn_S199, 0, 2, 1, 1)
        self.btn_V1939 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_V1939.setObjectName("btn_V1939")
        self.gridHeule.addWidget(self.btn_V1939, 0, 1, 1, 1)
        self.btn_G610 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_G610.setObjectName("btn_G610")
        self.gridHeule.addWidget(self.btn_G610, 0, 3, 1, 1)
        self.btn_V151 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_V151.setFont(font)
        self.btn_V151.setObjectName("btn_V151")
        self.gridHeule.addWidget(self.btn_V151, 0, 0, 1, 1)
        self.btn_G553 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_G553.setObjectName("btn_G553")
        self.gridHeule.addWidget(self.btn_G553, 1, 0, 1, 1)
        self.lb_heule = QtWidgets.QLabel(GraphsDialog)
        self.lb_heule.setGeometry(QtCore.QRect(20, 400, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Euphemia")
        font.setPointSize(14)
        font.setUnderline(True)
        self.lb_heule.setFont(font)
        self.lb_heule.setObjectName("lb_heule")

        self.retranslateUi(GraphsDialog)
        QtCore.QMetaObject.connectSlotsByName(GraphsDialog)

    def retranslateUi(self, GraphsDialog):
        _translate = QtCore.QCoreApplication.translate
        GraphsDialog.setWindowTitle(_translate("GraphsDialog", "New UDG"))
        self.lb_window.setText(_translate("GraphsDialog", "Unit Distance Graphs"))
        self.btn_T.setText(_translate("GraphsDialog", "T"))
        self.btn_K.setText(_translate("GraphsDialog", "K"))
        self.btn_L.setText(_translate("GraphsDialog", "L"))
        self.btn_J.setText(_translate("GraphsDialog", "J"))
        self.btn_H.setText(_translate("GraphsDialog", "H"))
        self.btn_V.setText(_translate("GraphsDialog", "V"))
        self.btn_U.setText(_translate("GraphsDialog", "U"))
        self.btn_W.setText(_translate("GraphsDialog", "W"))
        self.btn_M.setText(_translate("GraphsDialog", "M"))
        self.btn_G.setText(_translate("GraphsDialog", "G"))
        self.lb_degrey.setText(_translate("GraphsDialog", "De Grey\'s graphs:"))
        self.btn_pentagram.setText(_translate("GraphsDialog", "Pentagram"))
        self.btn_petersen.setText(_translate("GraphsDialog", "Petersen Graph"))
        self.btn_pentagon.setText(_translate("GraphsDialog", "Pentagon"))
        self.btn_moser.setText(_translate("GraphsDialog", "Moser\'s Spindle"))
        self.lb_additional.setText(_translate("GraphsDialog", "Additional graphs:"))
        self.btn_S199.setText(_translate("GraphsDialog", "S199"))
        self.btn_V1939.setText(_translate("GraphsDialog", "V1939"))
        self.btn_G610.setText(_translate("GraphsDialog", "G610"))
        self.btn_V151.setText(_translate("GraphsDialog", "V151"))
        self.btn_G553.setText(_translate("GraphsDialog", "G553"))
        self.lb_heule.setText(_translate("GraphsDialog", "Heule\'s graphs:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraphsDialog = QtWidgets.QDialog()
    ui = Ui_GraphsDialog()
    ui.setupUi(GraphsDialog)
    GraphsDialog.show()
    sys.exit(app.exec_())

