# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphs.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GraphsDialog(object):
    def setupUi(self, GraphsDialog):
        GraphsDialog.setObjectName("GraphsDialog")
        GraphsDialog.resize(1050, 666)
        self.lb_window = QtWidgets.QLabel(GraphsDialog)
        self.lb_window.setGeometry(QtCore.QRect(20, 20, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Euphemia")
        font.setPointSize(22)
        self.lb_window.setFont(font)
        self.lb_window.setObjectName("lb_window")
        self.gridLayoutWidget = QtWidgets.QWidget(GraphsDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 120, 421, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_T = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_T.setObjectName("btn_T")
        self.gridLayout.addWidget(self.btn_T, 1, 0, 1, 1)
        self.btn_K = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_K.setObjectName("btn_K")
        self.gridLayout.addWidget(self.btn_K, 0, 2, 1, 1)
        self.btn_L = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_L.setObjectName("btn_L")
        self.gridLayout.addWidget(self.btn_L, 0, 3, 1, 1)
        self.btn_J = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_J.setObjectName("btn_J")
        self.gridLayout.addWidget(self.btn_J, 0, 1, 1, 1)
        self.btn_H = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_H.setObjectName("btn_H")
        self.gridLayout.addWidget(self.btn_H, 0, 0, 1, 1)
        self.btn_V = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_V.setObjectName("btn_V")
        self.gridLayout.addWidget(self.btn_V, 1, 2, 1, 1)
        self.btn_U = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_U.setObjectName("btn_U")
        self.gridLayout.addWidget(self.btn_U, 1, 1, 1, 1)
        self.btn_W = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_W.setObjectName("btn_W")
        self.gridLayout.addWidget(self.btn_W, 1, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(GraphsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(480, 120, 160, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_M = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_M.setObjectName("btn_M")
        self.verticalLayout.addWidget(self.btn_M)
        self.btn_G = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_G.setObjectName("btn_G")
        self.verticalLayout.addWidget(self.btn_G)
        self.lb_degrey = QtWidgets.QLabel(GraphsDialog)
        self.lb_degrey.setGeometry(QtCore.QRect(20, 70, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Euphemia")
        font.setPointSize(14)
        font.setUnderline(True)
        self.lb_degrey.setFont(font)
        self.lb_degrey.setObjectName("lb_degrey")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(GraphsDialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 440, 421, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_pentagram = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_pentagram.setObjectName("btn_pentagram")
        self.gridLayout_2.addWidget(self.btn_pentagram, 0, 2, 1, 1)
        self.btn_petersen = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_petersen.setObjectName("btn_petersen")
        self.gridLayout_2.addWidget(self.btn_petersen, 0, 3, 1, 1)
        self.btn_pentagon = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_pentagon.setObjectName("btn_pentagon")
        self.gridLayout_2.addWidget(self.btn_pentagon, 0, 1, 1, 1)
        self.btn_moser = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_moser.setObjectName("btn_moser")
        self.gridLayout_2.addWidget(self.btn_moser, 0, 0, 1, 1)
        self.lb_additional = QtWidgets.QLabel(GraphsDialog)
        self.lb_additional.setGeometry(QtCore.QRect(20, 390, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Euphemia")
        font.setPointSize(14)
        font.setUnderline(True)
        self.lb_additional.setFont(font)
        self.lb_additional.setObjectName("lb_additional")

        self.retranslateUi(GraphsDialog)
        QtCore.QMetaObject.connectSlotsByName(GraphsDialog)

    def retranslateUi(self, GraphsDialog):
        _translate = QtCore.QCoreApplication.translate
        GraphsDialog.setWindowTitle(_translate("GraphsDialog", "New UDG"))
        self.lb_window.setText(_translate("GraphsDialog", "Unit Distance Graphs"))
        self.btn_T.setText(_translate("GraphsDialog", "T"))
        self.btn_K.setText(_translate("GraphsDialog", "K"))
        self.btn_L.setText(_translate("GraphsDialog", "L"))
        self.btn_J.setText(_translate("GraphsDialog", "J"))
        self.btn_H.setText(_translate("GraphsDialog", "H"))
        self.btn_V.setText(_translate("GraphsDialog", "V"))
        self.btn_U.setText(_translate("GraphsDialog", "U"))
        self.btn_W.setText(_translate("GraphsDialog", "W"))
        self.btn_M.setText(_translate("GraphsDialog", "M"))
        self.btn_G.setText(_translate("GraphsDialog", "G"))
        self.lb_degrey.setText(_translate("GraphsDialog", "De Grey\'s basic graphs:"))
        self.btn_pentagram.setText(_translate("GraphsDialog", "Pentagram"))
        self.btn_petersen.setText(_translate("GraphsDialog", "Petersen Graph"))
        self.btn_pentagon.setText(_translate("GraphsDialog", "Pentagon"))
        self.btn_moser.setText(_translate("GraphsDialog", "Moser\'s Spindle"))
        self.lb_additional.setText(_translate("GraphsDialog", "Additional graphs:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraphsDialog = QtWidgets.QDialog()
    ui = Ui_GraphsDialog()
    ui.setupUi(GraphsDialog)
    GraphsDialog.show()
    sys.exit(app.exec_())

